config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers  => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  root'products#index'  
    

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

resources :homes

resources :line_items do
    member do
      get 'add_qunatity'
      get 'reduce_quantity'
      post 'create'
    end
  end

  
    resources :carts

    resources :orderables

  
  resources :products 
  
  get ':category_id/1/products', to: 'products#index'

  resources :products do 
    member do
      get ':category_id/1/products', to: 'products#index'
      get ':category_id/2/products', to: 'products#index'
      get ':category_id/3/products', to: 'products#index'
    end
  end

  
  resources :profiles
  get "profiles/:id/edit" => "profiles#edit"

  get 'termscondition' => 'static_pages#termscondition'
  get 'faq' => 'static_pages#faq'
  get 'offers' => 'static_pages#offers'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :line_items
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :cart
	belongs_to :product
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * qunatity
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  validates :category_id, presence: true
  belongs_to :category

  has_many :line_items
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

  

app/models/user.rb
class User < ApplicationRecord
  after_create :save_profile  

  has_one :profile, :dependent => :destroy
  has_many :products
  has_one :cart
  
  

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email 
  validates_uniqueness_of :email
  validates :phone,:presence => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }


  attr_accessor :login
  # Include default devise modules. Others available are:
  # :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:lockable,
         :recoverable, :rememberable,:omniauthable,  :validatable, :confirmable, :omniauth_providers => [:github, :google_oauth2, :facebook, :linkedin], authentication_keys: [:login]



  def login
    @login || self.phone || self.username || self.email
  end
  
  def email_required?
    false
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email)= :value OR lower(phone)= :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:phone) || conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
end



  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end
    user
end
 
  def save_profile
    self.create_profile
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!
	def show 
		@cart = Cart.find(params[:id])
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :category, only:[:show, :edit, :update, :destroy]


	def show
		@category = Category.all
	end

	
	private
		def category_params
			params.require(:category).permit(:name)
		end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @homes = Product.all
  end

  def tc
    @tc = TC.all
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	 before_action :authenticate_user!
    
   def index
    @line_items = current_user.cart.line_items
    @line_item = LineItem.new
   end

  def create
    @line_items = LineItem.all
    @line_item = current_user.cart.line_items.create(product_id: params[:id])
        respond_to do |format|
            if @line_item.save
                format.js
            else 
                format.html
            end
        end
    end

  def destroy
     respond_to do |format|
            if @line_item.delete
                format.js
            else
                redirect_to :back , notice: "item is not added to cart"
            end
        end  
    end

  def add_quantity
     respond_to do |format|
            if @line_item.update(quantity: @line_item.quantity + 1)
                format.js
            else
                format.html
            end
        end
    end

  def reduce_quantity
     respond_to do |format|
            if @line_item.update(quantity: @line_item.quantity - 1)
                format.js
            else
                format.html
            end
        end
    end
  private

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id, :cart_id)
  end


  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	#before_action :category, only: %i[index, show]
	  def index
	  	if params[:id] 
	  	  @products = Product.where(category_id: params[:id])
	     else
	     	@products = Product.all
	     end
	  end

	  def show
	    @categories = Category.all
	  end

	  def new
	    @product = Product.new
	    @categories = Category.all
	    
	  end
	  
	  def create
	    @product = current_user.products.create(product_params)
	    if @product.save
	      redirect_to products_path
	    else
	      render :new
	    end
	  end

	  def edit
	  	@product = Product.find(params[:id])
	  end

	  def update
	    @product = Product.find(params[:id])
	    if @product.update(product_params)
	      redirect_to @product
	    else
	      render :new
	    end
	  end

	  def destroy
	    @product = Product.find(params[:id])
	    @product.destroy

	    	redirect_to root_path
	  end

	  private
	  def product_params
	    params.require(:product).permit(:name, :brand, :price, :category_id, :details, images:[])
	  end

	  # def category
	  # 	@categories = Category.find(params[:category_id])
	  # end

 end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
	def show 
		@profile = Profile.find(params[:id])
	end
    def edit
		@profile = Profile.find(params[:id])
	end
	def update
		@profile = Profile.find(params[:id])
		if @profile.update(profiles_params)
      		redirect_to @profile
    	else
      		render :edit
    	end
	end


	private
	def profiles_params
		params.require(:profile).permit(:first_name, :last_name, :gender, :age, :house_no, :street, :city, :state, :country, :pincode)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orderables_helper.rb
module OrderablesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cart/_cart.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Cart</h1>
  </div>
</section>

<div class="container mb-4">
  <div class="row">
    <div class="col-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Product</th>
              <th scope="col">Available</th>
              <th scope="col" class="text-center">Quantity</th>
              <th scope="col" class="text-right">Price</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cart.line_items.each do |line_item| %>
              <%= render 'line/cart_line_item' , :product => line_item.product , :line_item => line_item %>
            <% end %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>Sub-Total</td>
              <td class="text-right"><%= number_to_currency(@cart.sub_total) %></td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>Shipping</td>
              <td class="text-right">free</td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>
                <strong>Total</strong>
              </td>
              <td class="text-right">
                <strong><%= number_to_currency(@cart.sub_total) %></strong>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col mb-2">
      <div class="row">
        <div class="col-sm-12  col-md-4">
          <%= button_to "Continue Shopping", root_path , class: "btn btn-block btn-light" , method: :get%>
        </div>
        <% if(@current_cart.line_items.count !=0 ) %>
          <div class="col-sm-12  col-md-4">
            <%= button_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-lg btn-block btn-warning text-uppercase"%>
          </div>
          <div class="col-sm-12 col-md-4 text-right">
            <%= button_to "Checkout", new_order_path , method: :get,class: "btn btn-lg btn-block btn-success text-uppercase"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>




<%= form_with(url: cart_add_path) do |f|%>
  <%#= f.hidden_field id:, value: @product.id%>
  <%= f.number_field :quantity, value: 1, min: 1%>
  <%= f.submit "Add to Cart", remote: true%>
<% end %>

app/views/cart/cart.js.erb
$("#CartForm").html("<%= escape_javascript render('line_items/cart_line_item')%>");

app/views/cart/show.html.erb
<p>show#cart</p>

app/views/line_items/_cart_line_item.html.erb
<tr>
  <td><%= link_to product do%>
    <% if product.images? %>
      <%= image_tag product.image.url , size:"90x90"%>
    <% else %>
      <%= image_tag "no_image.png", size:"90x90" %>
    <%end%>
  <%end %>
  x
  <%= line_item.quantity %>
</td>
<td><%= product.name %></td>
<td>In stock</td>
<td class="text-center">
  <!-- reduce -->
  <%=link_to line_item_reduce_path(:id => line_item) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
  <i class="glyphicon glyphicon-minus" style="color:white;"></i>

<% end %>
<!-- add -->
<%=link_to line_item_add_path(:id => line_item) , method: :post , class: "btn btn-success" , style: "margin-top:15px;" do %>
<i class="glyphicon glyphicon-plus" style="color:white;"></i>
<% end %>
</td>
<td class="text-right"><%= product.price %>
$</td>
<td class="text-right">
<!-- Remove -->
<%=link_to line_item_path(line_item) ,method: :delete ,class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
<i class="fa fa-trash"></i>
<% end %>
</td>
</tr>

app/views/line_items/_line_item.html.erb
  <div class="modal-body">
    <div id="all-line-items">
       <% @line_items.each do |item| %>
        <%= image_tag item.product.images.first, style: "width: 100px;height: 100px;" %><br>
        Name: <%= item.product.name %><br>
        Brand: <%= item.product.brand %><br>
        <h5>Price: <%= item.product.price %></h5><br>
        Details: <%= item.product.details %><br>
        <div class="btn-group" role="group" aria-label="Basic outlined example">
        <%= button_to "+", add_quantity_line_item_url:(@line_item), class:"btn btn-dark", remote: true%>
        <%= button_to "-", reduce_quantity_line_item_url:(@line_item), class:"btn btn-dark", remote: true%>
        </div>
        
        <div class="btn-group mr-2" role="group" aria-label="First group">
         Sizes:
          <button type="button" class="btn btn-outline-dark">6</button>
          <button type="button" class="btn btn-outline-dark">7</button>
          <button type="button" class="btn btn-outline-dark">8</button>
          <button type="button" class="btn btn-outline-dark">9</button>
          <button type="button" class="btn btn-outline-dark">10</button>
          <button type="button" class="btn btn-outline-dark">1C</button>
          <button type="button" class="btn btn-outline-dark">2C</button>
          <button type="button" class="btn btn-outline-dark">3C</button>
          <button type="button" class="btn btn-outline-dark">4C</button>
          <button type="button" class="btn btn-outline-dark">5C</button>
        </div>
        
        <div id = "QuantityStatus<%#=item.id%>">
        Quantity: <%#= item.quantity %><br>
        Price: <%#= item.product.price * item.quantity%><br>
        </div>
    <% end %>
    </div>
  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-dark">Buy Now</button>
      </div>

app/views/line_items/_product_show.html.erb
<div id="total_cart_items">
<div class="container">
  <div class="card">
    <div class="container">
      <div class="wrapper row">
        <div class="preview col-md-6">

          
          </div>
         /div>
        <div class="details col-md-6">
          <h3 class="product-title"><%= @product.name %></h3>
          <div class="rating">
            <div class="stars">
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
            </div>
          </div>
          <p class="product-description"><%= @product.details %></p>
          <h4 class="price">current price:
            <span>$<%= @product.price %></span></h4>
            of buyers enjoyed this product!
          <h5 class="sizes">sizes:
            <span class="size" data-toggle="tooltip" title="Uk-6">6</span>
            <span class="size" data-toggle="tooltip" title="UK-7">7</span>
            <span class="size" data-toggle="tooltip" title="Uk-8">8</span>
            <span class="size" data-toggle="tooltip" title="Uk-9">9</span>
            <span class="size" data-toggle="tooltip" title="Uk-10">10</span>
            <span class="size" data-toggle="tooltip" title="1C">1</span>
            <span class="size" data-toggle="tooltip" title="2C">2</span>
            <span class="size" data-toggle="tooltip" title="3C">3</span>
            <span class="size" data-toggle="tooltip" title="4C">4</span>
            <span class="size" data-toggle="tooltip" title="5C">5</span>
          </h5>
          <div class="action">
              <%if !@current_cart.products.include?(product)%>
              <%# if logged_in? %>
                <!-- Add to Basket -->
                <%=button_to line_items_path(:product_id => product.id), class: "btn btn-outline-dark" , style: "margin-top:15px;" , params:{productID: product.id} do %>
                <i class="glyphicon glyphicon-plus" style="color:black;"></i>
                ADD TO CART
              <% end %>
              <%# end %>
              <%else %>

                <!-- See lineItem section below for explanation of line_item links -->
                <ul class="users">
                  <!-- <li> -->
                  <!-- <%#= link_to "Add one", line_item_add_path(:id => line_item), method: :post %> -->

                  <!-- reduce -->
                  <%=link_to line_item_reduce_path(:id =>@current_cart.line_items.find_by(product_id: product.id)) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
                  <i class="glyphicon glyphicon-minus" style="color:black;"></i>
                  Reduce
                <% end %>

                <!-- add -->
                <%=link_to line_item_add_path(:id => @current_cart.line_items.find_by(product_id: product.id)) , method: :post , class: "btn btn-success" , style: "margin-top:15px;" do %>
                <i class="glyphicon glyphicon-plus" style="color:black;"></i>
                Add
              <% end %>

              <!-- Remove -->
              <%=link_to line_item_path(@current_cart.line_items.find_by(product_id: product.id)) ,method: :delete ,class: "btn btn-warning" , style: "margin-top:15px;" do %>
              <i class="glyphicon glyphicon-remove" style="color:black;"></i>
              Remove Item
            <% end %>

            <li>Quantity:
              <%= @current_cart.line_items.find_by(product_id: product.id).quantity %>
              | Total Price:
              <%#= number_to_currency(@current_cart.line_items.find_by(product_id: product.id).total_price) %>
              <hr class="style18"/>
          </ul>
        <%end %>
      </p>

      <p>
        <% if current_user && current_user.admin%>
          <%= link_to edit_product_path(product) do %>
          <i class="glyphic
          on glyphicon-pencil" style="color:darkgray"></i>
          Edit
        <% end %>
        or
        <!-- Basket -->
        <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="glyphicon glyphicon-fire" style="color:firebrick"></i>
        Destroy
      <% end %>
    <% end %>
  </p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/line_items/_quantity.html.erb
Quantity: <%= item.quantity %><br>
   Price: <%= item.product.price * item.quantity%><br>

app/views/line_items/add_quantity.js.erb
$("#LineItemsModal").html("<%= escape_javascript render('line_items/line_item'%>");

app/views/line_items/create.js.erb
$("#LineItemsModal").html("<%= escape_javascript render('line_items/line_item')%>");

app/views/line_items/index.js.erb
$("#LineItemsModal").html("<%= escape_javascript render('line_items/line_item')%>");	

app/views/line_items/reduce_quantity.js.erb
$("#LineItemsModal").html("<%= escape_javascript render('line_items/line_item')%>");

app/views/products/edit.html.erb
<center><%= form_for @product do |f| %>

    <div>
    <%=f.label :Name %>
    <%= f.text_field :name %><br />
    </div>

    <div>
      <%= f.label :Brand %>
      <%= f.select :brand, [['Adidas','Adidas'],['Nike','Nike'],['Puma','Puma'],['Reebok','Reebok']] %><br />
    </div>

    <div>
    <%=f.label :Price %>
    <%= f.text_field :price %><br />
    </div>
    
    <!-- <div>
      <%#= f.label :size %>
      <%#= f.select :size, [['6','6'],['7','7'],['8','8'],['9','9'],['10','10'],['1C','1C'],['2C','2C'],['3C','3C'],['4C','4C'],['5C','5C']] %><br />
    </div> -->
    
    <div>
    <%=f.label :Details %>
    <%= f.text_field :details %><br />
    </div>

    <div>
      <%= f.label :images %>
      <%= f.file_field :images, multiple: true %>
    </div>

    <div>
      <%= f.label :category %>
      <%= f.select :category_id, options_for_select(@categories.collect {|cat| [cat.name, cat.id]}) %><br />
   </div>

    <%= f.submit %>
  <% end %>

</center>

  

app/views/products/index.html.erb
<div class="container text-left">
  <div class="row" style="width:100%">
    <% @products.each do |product| %>
    <div class="col-4">
   
      <%= link_to (product) do %>
        <div class="card" style="width: 18rem;, height: 200px;">
        <% if product.images.attached? %>
          <%= image_tag product.images.first, width: "285px" ,height: "200px"%>
        <% end %>
      </div>
      <%end%>
        <div class="card-body">
          Name :<%= product.name %><br>
          Brand :<%= product.brand %><br>
          <h5>MRP ₹:<%= product.price %></h5><br>
        </div>
        
        </div>
       <%end%>
  </div>

</div>

<% if current_user && current_user.admin%>
  <%= link_to raw("<i class=\"icon-search icon-white\">Create New Product</i>"), 
           new_product_path, class: "btn btn-outline-dark"%>
<%end%>

app/views/products/new.html.erb
<center><%= form_for @product do |f| %>

    <div>
    <%=f.label :Name %>
    <%= f.text_field :name %><br />
    </div>

    <div>
      <%= f.label :Brand %>
      <%= f.select :brand, [['Adidas','Adidas'],['Nike','Nike'],['Puma','Puma'],['Reebok','Reebok']] %><br />
    </div>

    <div>
    <%=f.label :Price %>
    <%= f.text_field :price %><br />
    </div>
    
    <!-- <div>
      <%#= f.label :size %>
      <%#= f.select :size, [['6','6'],['7','7'],['8','8'],['9','9'],['10','10'],['1C','1C'],['2C','2C'],['3C','3C'],['4C','4C'],['5C','5C']] %><br />
    </div>
     -->
    <div>
    <%=f.label :Details %>
    <%= f.text_field :details %><br />
    </div>

    <div>
      <%= f.label :images %>
      <%= f.file_field :images, multiple: true %>
    </div>

   <div>
      <%= f.label :category %>
      <%= f.select :category_id, options_for_select(@categories.collect{|cat| [cat.name, cat.id]}) %><br />
   </div>


  <%= f.submit %>
  <% end %>

</center>

  

app/views/products/show.html.erb
<div class="container text-center">
  <div class="row-1">
    <% if @product.images.attached? %>
      <% @product.images.each do |image| %>
          <%= image_tag image, width: "300px", height: "200px"%>
      <% end %>
    <%end%>
        <div class="row-2">
          Name :<%= @product.name %><br />
          Brand :<%= @product.brand %><br />
          Price :<%= @product.price %><br />
          Details :<%=@product.details%><br />
          
        </div>
        <div>
  <% if user_signed_in? && current_user.cart.line_items.find_by(product_id: @product.id).present?%>
    <%=  link_to "Add to Cart", line_items_path, class: "btn btn-dark", data: {bs_target: "#LineItems", bs_toggle: "modal", remote: true}%>
  <% elsif user_signed_in? %>
    <%= link_to "Add to Cart", line_item_path(id: @product), class: "btn btn-dark", data: {bs_target: "#LineItems", bs_toggle: "modal", remote:true}, method: :post%>
  <% else %>
    <%=  link_to "Add to Cart", user_session_path, class: "btn btn-dark" %>
  <% end %>
    </div>

<!-- Modal -->
<div class="modal fade" id="LineItems" tabindex="-1" aria-labelledby="LineItemsLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="LineItemsLabel">Line Cart</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div id="LineItemsModal">
        
      </div>

    </div>
  </div>
</div>







<div >
<% if current_user && current_user.admin%>
<%= link_to raw("<i class=\"icon-search icon-white\">Edit</i>"), 
           edit_product_path(@product), class: "btn btn-outline-dark"%>

<%= link_to raw("<i class=\"icon-search icon-white\">Delete</i>"), 
           product_path(@product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-dark"%>

<% end %>

<%= link_to raw("<i class=\"icon-search icon-white\">Back</i>"), 
           products_path(@product), class: "btn btn-outline-dark"%>
</div>

</div>
</div>

app/views/profiles/edit.html.erb
<center><form class="form-horizontal center bg-light" role="form">
<h2>Welcome to Boothouse</h2>

<%= form_for @profile do |f| %>
    <div class="field">
        <%= f.label :first_name, "First name:", class: "col-md-2 control-label"   %>
        <%= f.text_field :first_name %><br /><br />
    </div>
    <div class="field">
        <%= f.label :last_name , "Last name:", class: "col-md-2 control-label" %>
        <%= f.text_field :last_name %><br /><br />
    </div>
    <div class="field">
        <%= f.label :gender,'Gender', class: "col-md-1 control-label" %>
        <%= f.label :Male %>
        <%= f.radio_button :gender, 'Male', :checked => true, class: "col-md-1 control-label" %>
        <%= f.label :Female %>
        <%= f.radio_button :gender, 'Female', :checked => true, class: "col-md-1 control-label" %> <br /><br />
    </div>
    <div class="field">
        <%= f.label :age, "Age:", class: "col-md-2 control-label" %>
        <%= f.text_field :age %><br /><br />
    </div>

    <div class="field">
        <%= f.label :house_no,"House no.:", class: "col-md-2 control-label"%>
        <%= f.text_field :house_no %><br /><br />
    </div>
    <div class="field">
        <%= f.label :street,"Street:", class: "col-md-2 control-label" %>
        <%= f.text_field :street %><br /><br />
    </div>
    <div class="field">
        <%= f.label :city, "City:", class: "col-md-2 control-label" %>
        <%= f.text_field :city %><br /><br />
    </div>
    <div class="field">
        <%= f.label :state, "State:", class: "col-md-2 control-label" %>
        <%= f.text_field :state %><br /><br />
    </div>
    <div class="field">
        <%= f.label :country, "Country:", class: "col-md-2 control-label" %>
        <%= f.text_field :country %><br /><br />
    </div>
    <div class="field">
        <%= f.label :pincode, "Pincode:", class: "col-md-2 control-label" %>
        <%= f.text_field :pincode %><br /><br />
    </div>
    <div class="field">
        <div class="col-md-4">
            <%= f.submit  nil ,class: 'btn btn-outline-dark'  %>
        </div>
    </div>  
<% end %>
</form>
</center>

<%=link_to "Back", products_path%>

app/views/profiles/index.html.erb
<% @profiles.each do |profile| %>
    <li><a href="<%= profiles_path(profile) %>">
        <%= profile.first_name%>
        <%= profile.last_name%>
        <%= profile.gender%>
        <%= profile.age%>
        <%= profile.house_no%>
        <%= profile.street%>
        <%= profile.city%>
        <%= profile.state%>
        <%= profile.country%>
        <%= profile.pincode%>
        </a>
     </li> 
  <% end %>

app/views/profiles/new.html.erb
<form class="form-horizontal center bg-light" role="form">
    <h1><b>Welcome to Boothouse</b></h1>

  <%= form_for @profile do |f| %>
    <div class="field">
        <%= f.label :first_name, "First name:", class: "col-md-4 control-label"   %>
        <%= f.text_field :first_name %><br /><br />
    </div>
    <div class="field">
        <%= f.label :last_name , "Last name:", class: "col-md-4 control-label" %>
        <%= f.text_field :last_name %><br /><br />
    </div>
    <div class="field">
        <%= f.label :gender, 'gender: %>
        <%= f.label :Male %>
        <%= f.radio_button :gender, 'Male' %>
        <%= f.label a:Female %>
        <%= f.radio_button :gender, 'Female' %> <br /><br />
    </div>
    <div class="field">
        <%= f.label :age %>
        <%= f.text_field :age %><br /><br />
    </div>

    <div class="field">
        <%= f.label :house_no %>
        <%= f.text_field :house_no %><br /><br />
    </div>
    <div class="field">
        <%= f.label :street %>
        <%= f.text_field :street %><br /><br />
    </div>
    <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city %><br /><br />
    </div>
    <div class="field">
        <%= f.label :state %>
        <%= f.text_field :state %><br /><br />
    </div>
    <div class="field">
        <%= f.label :country %>
        <%= f.text_field :country %><br /><br />
    </div>
    <div class="field">
        <%= f.label :pincode %>
        <%= f.text_field :pincode %><br /><br />
    </div>
    <div class="field">
        <%= f.submit%>
    </div>  
<% end %>


<%=button_to 'Back', products_path%>

app/views/profiles/show.html.erb
<p><%= @profile.first_name%></p>
<p><%= @profile.last_name%></p>
<p><%= @profile.gender%></p>
<p><%= @profile.age%></p>
<p><%= @profile.house_no%></p>
<p><%= @profile.street%></p>
<p><%= @profile.city%></p>
<p><%= @profile.state%></p>
<p><%= @profile.country%></p>
<p><%= @profile.pincode%></p>

<div>
  <%= button_to "Edit", edit_profile_path(@profile) %><%= button_to "Destroy",profile_path(@profile),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
</div>
  
<%= link_to 'Back'%>